#!/bin/bash

# Abort on any kind of error
set -e -o pipefail

# Returns true if repo has uncommitted changes
__isDirty()
{
	# see http://stackoverflow.com/a/2659808
	! git diff-index --quiet HEAD
}

if __isDirty ; then
	echo "There are uncommited changes. Please commit them first."
	exit 1
fi

# Obtain the package name and version
NAME=$(dpkg-parsechangelog --show-field=Source)
VERSION=$(dpkg-parsechangelog --show-field=Version)

git clean -dxf

msbuild /t:Build /p:Configuration=Release build/DigitaleBriefwahl.proj

mv output/Release/DigitaleBriefwahl.Launcher/net472 LauncherBin

rm -rf packages
rm -rf output
rm -rf lib

# Create the source package
debuild $DEBUILD_ADDITIONAL_OPTS -S -sa -Zbzip2 -i'.*' \
  --tar-ignore=.vscode \
  --tar-ignore=.idea \
  --tar-ignore=.git \
  --tar-ignore=.github \
  --tar-ignore=DigitaleBriefwahl/build \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl.Desktop \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl.ExceptionHandling \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl.ExceptionHandlingTests \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl.Launcher \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahl.Launcher.Mac \
  --tar-ignore=DigitaleBriefwahl/DigitaleBriefwahlTests \
  --tar-ignore=DigitaleBriefwahl/DigiTally \
  --tar-ignore=DigitaleBriefwahl/DigiTallyTests \
  --tar-ignore=DigitaleBriefwahl/macos \
  --tar-ignore=DigitaleBriefwahl/Packer \
  --tar-ignore=DigitaleBriefwahl/SquirrelBuild
