name: "Build and Test"
on:
  push:
    branches: [master]
    # Trigger on release tags
    tags: [ 'v[0-9]+*' ]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: "Build and Test"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: '0'

    - name: Install .NET Core
      uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --logger "html;logfilename=TestResults.html"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: Test Results (${{matrix.os}})
        path: "**/TestResults/TestResults.html"
