name: "Build and Test"
on:
  push:
    branches: [master]
    # Trigger on release tags
    tags: [ 'v[0-9]+*' ]
  pull_request:

jobs:
  build-and-test:
    name: "Build and Test"
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: '0'

    - name: Install .NET Core
      uses: actions/setup-dotnet@4d6c8fcf3c8f7a60068d26b594648e99df24cee3 # v4.0.0
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --logger "html;logfilename=TestResults.html"

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: Test Results (${{matrix.os}})
        path: "**/TestResults/TestResults.html"
